// <auto-generated />
using System;
using Book_Reservation.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Book_Reservation.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250319140120_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Book_Reservation.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 3, 19, 10, 1, 18, 705, DateTimeKind.Local).AddTicks(512),
                            Email = "john.doe@example.com",
                            Name = "John Doe",
                            PasswordHash = "$2a$11$3sjmKFI6czID1UxBafuo1Okg24EUPTF0vvLZ8Q0blxawHcS3Itsam"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 3, 19, 10, 1, 19, 39, DateTimeKind.Local).AddTicks(870),
                            Email = "jane.smith@example.com",
                            Name = "Jane Smith",
                            PasswordHash = "$2a$11$8M1dU/7dVOdgsFf9BG4zx.v.6u5Lo1LPChSn6PzpBl6ZiTK9Vmg5i"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
