// <auto-generated />
using System;
using Book_Reservation.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Book_Reservation.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250319140904_FixSeedData")]
    partial class FixSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Book_Reservation.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 3, 19, 10, 9, 3, 674, DateTimeKind.Local).AddTicks(3625),
                            Email = "john.doe@example.com",
                            Name = "John Doe",
                            PasswordHash = "$2a$12$F3X.5xP72vGjWcHMG6KOfu2G9pGvP1FsNhf0FnhBQ87Eb.c3HtG1W"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 3, 19, 10, 9, 3, 677, DateTimeKind.Local).AddTicks(3190),
                            Email = "jane.smith@example.com",
                            Name = "Jane Smith",
                            PasswordHash = "$2a$12$A9NZXOr02hz7.pWBq4l3HeG.eUX3MHRPugMY1MKIE/3J1GucPiKmK"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
